export default function TermsPage() {
  return (
    <article className="prose prose-invert prose-sm max-w-2xl mx-auto animate-fade-in py-4">
      <h1 className="font-display text-3xl text-echo-50">Terms of Use</h1>
      <p className="text-ink-400 text-sm">
        Last updated: {new Date().toISOString().slice(0, 10)}. EroticEcho is an
        adult (18+) interactive fiction product.
      </p>
      <h2 className="text-echo-100">1. Eligibility</h2>
      <p className="text-ink-300">
        You must be at least 18 years old (or the age of majority where you
        live). By using the service you represent that you meet this
        requirement.
      </p>
      <h2 className="text-echo-100">2. Adult content</h2>
      <p className="text-ink-300">
        The service generates explicit erotic fiction between consenting adult
        characters. Content involving minors is prohibited and technically
        blocked. Fantasy themes (including CNC framed as adult roleplay) are
        fictional.
      </p>
      <h2 className="text-echo-100">3. Accounts & plans</h2>
      <p className="text-ink-300">
        Free and paid plans apply usage limits to AI generation. You are
        responsible for keeping credentials secure. Owner/admin accounts may
        have unrestricted access for operations.
      </p>
      <h2 className="text-echo-100">4. Acceptable use</h2>
      <p className="text-ink-300">
        Do not attempt to generate illegal content, abuse the API, scrape the
        service, reverse engineer beyond fair use, or resell access without
        permission.
      </p>
      <h2 className="text-echo-100">5. AI disclaimers</h2>
      <p className="text-ink-300">
        Outputs are generated by AI and may be inaccurate, unexpected, or
        offensive. Stories are not professional advice. You use outputs at your
        own risk.
      </p>
      <h2 className="text-echo-100">6. Payments</h2>
      <p className="text-ink-300">
        Paid plans are billed via the configured payment processor (e.g.
        Stripe). Refunds follow the processor and local law. Demo billing may
        exist in non-production environments.
      </p>
      <h2 className="text-echo-100">7. Termination</h2>
      <p className="text-ink-300">
        We may suspend accounts that violate these terms or applicable law.
      </p>
      <h2 className="text-echo-100">8. Contact</h2>
      <p className="text-ink-300">
        For product issues, contact the operator of this deployment.
      </p>
    </article>
  );
}
